version: '3'
services:
  data-processor:
    build: .
    environment:
      - SQS_QUEUE_NAME=your-queue-name
      - DB_HOST=your-db-host
      - DB_USER=your-db-user
      - DB_PASSWORD=your-db-password
      - DB_DATABASE=your-db-database
    restart: always
